### ISSUE TITLE
Export xls not working with Jmesa 3.0.1  with Poi 3.8 jar

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bgould/jmesa#343]
```
What steps will reproduce the problem?
1. export xls is not working.
2. getting NoSuchMethodError
3. I tried with Poi 3.6 ,3.7 ,3.8 and 3.9 all getting exception

What is the expected output? What do you see instead?
export xls works fine.
What version of the product are you using? On what operating system?
Jmesa-3.0.1.jar,spring-3.0,windows 7

Please provide any additional information below.
Is Jmesa supports poi3.8 for export option 


getting  below exception 
java.lang.NoSuchMethodError:org.apache.poi.hssf.usermodel.HSSFCell.setCellValues
(Lorg/apache/poi/hssf/usermodel/HSSFRichTextString;)V
```

Original issue reported on code.google.com by `rajamoha...@gmail.com` on 30 Aug 2012 at 3:44
