### ISSUE TITLE
Excel Export not working with POI 3.8

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bgould/jmesa#347]
```
What steps will reproduce the problem?
1. Jmesa table excel export not working with poi-3.8 version. Is it compatible 
with poi-3.8 ? Please let me know
2.
3.

What is the expected output? What do you see instead?
I get the following error when I try to export it - 
java.lang.NoSuchMethodError: 
org.apache.poi.hssf.usermodel.HSSFCell.setCellValue(Lorg/apache/poi/hssf/usermod
el/HSSFRichTextString;)V

What version of the product are you using? On what operating system?

I am using JMesa 3.0.4 and Windows 7

Please provide any additional information below. I apprecite if you help me in 
resolving this issue. Thanks!!

```

Original issue reported on code.google.com by `cmank...@tacticaltrust.com` on 6 Nov 2012 at 10:09
